# Generated by Django 5.2.3 on 2025-06-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoftl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(max_length=200)),
                ('Rider_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoftl_app.rider')),
                ('admin_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoftl_app.admin')),
            ],
        ),
    ]
