# Generated by Django 5.2.3 on 2025-06-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decoftl_app', '0003_alter_admin_username_alter_rider_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rider',
            new_name='Riders',
        ),
    ]
