# Generated by Django 5.2.3 on 2025-06-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decoftl_app', '0005_rename_riders_rider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rider',
            new_name='Riders',
        ),
    ]
