# Generated by Django 5.2.3 on 2025-06-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoftl_app', '0007_rename_riders_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
