# Generated by Django 5.2.3 on 2025-06-10 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoftl_app', '0008_alter_rider_username_remove_admin_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rider_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracker_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(max_length=200)),
                ('admin_tracker', models.CharField(max_length=200, unique=True)),
                ('Rider_tracker', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Rider',
        ),
        migrations.AddField(
            model_name='rider_1',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoftl_app.tracker_1'),
        ),
        migrations.AddField(
            model_name='admin_1',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoftl_app.tracker_1'),
        ),
    ]
