# Generated by Django 5.2.3 on 2025-06-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decoftl_app', '0009_admin_1_rider_1_tracker_1_delete_admin_delete_rider_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_1',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='Rider_1',
            new_name='Rider',
        ),
        migrations.RenameModel(
            old_name='Tracker_1',
            new_name='Tracker',
        ),
    ]
