# Generated by Django 5.2.3 on 2025-06-10 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoftl_app', '0010_rename_admin_1_admin_rename_rider_1_rider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rider',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='admin_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoftl_app.rider'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoftl_app.admin'),
        ),
    ]
